sudo: false

language: node_js

os:
  - linux
  # - osx

node_js:
  - $NODE_VERSION

install:
  - yarn

script:
  - yarn test:coverage
  - yarn release
  - yarn package:binary
  # - yarn publish:release
  # - yarn publish:binary

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

env:
  matrix:
    # - NODE_VERSION="9"
    - NODE_VERSION="10"
    # - NODE_VERSION="11"
    # - NODE_VERSION="12"
    # - NODE_VERSION="13"