image: Visual Studio 2017

install:
  - git config --global credential.helper store
  - ps: Add-Content "$HOME\.git-credentials" "https://$($env:NODE_PRE_GYP_GITHUB_TOKEN):x-oauth-basic@github.com`n"
  - git config --global user.email "jpshor@gmail.com"
  - git config --global user.name "Josh Shor"
  - ps: Install-Product node $env:NODE_VERSION $env:platform
  - yarn global add windows-build-tools
  - yarn

test_script:
  - yarn test

build_script:
  - yarn release
  - yarn package:binary

on_success:
  - echo "publishing now..."
  # - yarn publish:binary

platform:
  # - x86
  - x64

environment:
  matrix:
    # - NODE_VERSION: '9'
    - NODE_VERSION: '10'
    # - NODE_VERSION: '11'
    # - NODE_VERSION: '12'
    # - NODE_VERSION: '13'